src/t2/paginasweb/config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :pages
  resources :webpages

  get 'webpages/new'
  get 'webpages/create'
  get 'webpages/update'
  get 'webpages/edit'
  get 'webpages/destroy'
  get 'webpages/index'
  get 'webpages/show'

  post 'authenticate', to: 'authentication#authenticate'

  root 'webpages#index'
end

src/t2/paginasweb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/t2/paginasweb/app/models/item.rb
class Item < ApplicationRecord
end

src/t2/paginasweb/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

src/t2/paginasweb/app/models/webpage.rb
class Webpage < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
end

src/t2/paginasweb/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  before_action :authenticate_request
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
end

src/t2/paginasweb/app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

src/t2/paginasweb/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    if @item.save
      render :show, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      render :show, status: :ok, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description)
    end
end

src/t2/paginasweb/app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
  # caches_page :index, :show

  def new
    @webpage = Webpage.new
  end

  def create
    @webpage = Webpage.new(webpage_params)

    respond_to do |format|
      if @webpage.save
        format.html { redirect_to @webpage, notice: 'Webpage was successfully created.' }
        format.json { render :show, status: :created, location: @webpage }
      else
        format.html { render :new }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @webpage.update(webpage_params)
        # expire_page webpages_path
        # expire_page webpages_path(@webpage)
        # expire_page "/"

        format.html { redirect_to @webpage, notice: 'A página foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @webpage }
      else
        format.html { render :edit }
        format.json { render json: @webpage.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @webpage = Webpage.find(params[:id])
  end

  def destroy
    @webpage = Webpage.find(params[:id])
    @webpage.destroy
 
    redirect_to webpages_path
  end

  def index
    @webpages = Webpage.all
  end

  def show
    @webpage = Webpage.find(params[:id])
  end

  private
    def webpage_params
      params.require(:webpage).permit(:title, :description, :body, :author, :created_at, :updated_at)
    end

end

src/t2/paginasweb/app/helpers/application_helper.rb
module ApplicationHelper
end

src/t2/paginasweb/app/helpers/webpages_helper.rb
module WebpagesHelper
end

src/t2/paginasweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paginasweb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

src/t2/paginasweb/app/views/webpages/_form.html.erb
<%= form_with scope: :webpage, url: webpages_path, local: true do |form| %>

  <p>
    <%= form.label t('title') %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label t('description') %><br>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.label t('body') %><br>
    <%= form.text_area :body %>
  </p>
  
  <p>
    <%= form.label t('author') %><br>
    <%= form.text_area :author %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

src/t2/paginasweb/app/views/webpages/create.html.erb
<h1>Webpages#create</h1>
<p>Find me in app/views/webpages/create.html.erb</p>

src/t2/paginasweb/app/views/webpages/destroy.html.erb
<h1>Webpages#destroy</h1>
<p>Find me in app/views/webpages/destroy.html.erb</p>

src/t2/paginasweb/app/views/webpages/edit.html.erb
<h1>Editar Página</h1>

<%= render 'form' %>

<%= link_to 'Show', @webpage %> |
<%= link_to 'Voltar', webpages_path %>

src/t2/paginasweb/app/views/webpages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webpages</h1>

<table>
  <thead>
    <tr>
      <th><%= t('title') %></th>
      <th><%= t('description') %></th>
      <th><%= t('body') %></th>
      <th><%= t('author') %></th>
      <th><%= t('created_at') %></th>
      <th><%= t('updated_at') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webpages.each do |webpage| %>
      <tr>
        <td><%= webpage.title %></td>
        <td><%= webpage.description %></td>
        <td><%= webpage.body %></td>
        <td><%= webpage.author %></td>
        <td><%= l(webpage.created_at) %></td>
        <td><%= l(webpage.updated_at) %></td>
        <td><%= link_to t('show'), webpage %></td>
        <td><%= link_to t('edit'), edit_webpage_path(webpage) %></td>
        <td><%= link_to t('destroy'), webpage, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova página', new_webpage_path %>

src/t2/paginasweb/app/views/webpages/new.html.erb
<h1>Nova página</h1>

<%= render 'form' %>

<%= link_to 'Voltar', webpages_path %>

src/t2/paginasweb/app/views/webpages/show.html.erb
<h1>Páginas</h1>

<p>
  <strong><%=t('title') %>:</strong>
  <%= @webpage.title %>
</p>

<p>
  <strong><%=t('description') %>:</strong>
  <%= @webpage.description %>
</p>

<p>
  <strong><%=t('body') %>:</strong>
  <%= @webpage.body %>
</p>

<p>
  <strong><%=t('author') %>:</strong>
  <%= @webpage.author %>
</p>

<%= link_to 'Back', webpages_path %>

src/t2/paginasweb/app/views/webpages/update.html.erb
<h1>Webpages#update</h1>
<p>Find me in app/views/webpages/update.html.erb</p>